# Generated by Django 4.2.3 on 2023-07-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('conversion_slug', models.SlugField(unique=True, verbose_name='Conversion Slug')),
                ('side_picture', models.ImageField(upload_to='conversions/', verbose_name='side picture')),
                ('veichle_cost', models.IntegerField(blank=True, null=True, verbose_name='Veichle cost')),
                ('conversion_cost', models.IntegerField(blank=True, null=True, verbose_name='Conversion cost')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('interior1', models.ImageField(blank=True, null=True, upload_to='conversions/', verbose_name='Interior1')),
                ('interior2', models.ImageField(blank=True, null=True, upload_to='conversions/', verbose_name='Interior2')),
                ('interior3', models.ImageField(blank=True, null=True, upload_to='conversions/', verbose_name='Interior3')),
                ('interior4', models.ImageField(blank=True, null=True, upload_to='conversions/', verbose_name='Interior4')),
                ('outro', models.TextField(blank=True, null=True, verbose_name='outro')),
                ('c_type', models.PositiveBigIntegerField(choices=[(0, 'Van'), (1, 'Rv')], db_index=True, verbose_name='conversion type')),
                ('verification_status', models.PositiveBigIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Declined')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'conversion',
                'verbose_name_plural': 'conversions',
            },
        ),
        migrations.CreateModel(
            name='GadgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.ImageField(upload_to='gadgettypes/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'gadget type',
                'verbose_name_plural': 'gadget types',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('svg_loggo_code', models.TextField(verbose_name='Font awesome logo svg')),
            ],
            options={
                'verbose_name': 'social',
                'verbose_name_plural': 'socials',
            },
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('picture', models.ImageField(upload_to='gadgets/', verbose_name='picture')),
                ('aff_link', models.URLField(verbose_name='affiliate link')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget', to='conversions.conversion', verbose_name='conversion')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadget', to='conversions.gadgettype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'gadget',
                'verbose_name_plural': 'gadgets',
            },
        ),
        migrations.CreateModel(
            name='ConversionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='link')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_social', to='conversions.conversion', verbose_name='conversion')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_social', to='conversions.social', verbose_name='social')),
            ],
            options={
                'verbose_name': 'conversion social',
                'verbose_name_plural': 'conversion socials',
            },
        ),
    ]
