# Generated by Django 4.2.3 on 2023-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionsocial',
            name='social_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social username/@...'),
        ),
    ]
