# Generated by Django 4.2.3 on 2023-07-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_conversionsocial_social_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='conversions.conversion', verbose_name='conversion'),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='conversions.gadgettype', verbose_name='type'),
        ),
    ]
