# Generated by Django 4.2.2 on 2023-06-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('icon', models.ImageField(upload_to='profile/profileicons', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'profile icon',
                'verbose_name_plural': 'profile icons',
            },
        ),
    ]
